version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: circleci-node-assets-{{ checksum "package.json" }}-v2
      - run: npm install
      - save_cache:
          key: circleci-node-assets-{{ checksum "package.json" }}-v2
          paths:
            - node_modules

      - run: npm run coverage

      - run:
          name: post codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: dist/report/

      - store_artifacts:
          path: dist/


  release:
    docker:
      - image: circleci/node:9.2
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          key: circleci-node-assets-{{ checksum "package.json" }}-v2
      - run: npm install
      - save_cache:
          key: circleci-node-assets-{{ checksum "package.json" }}-v2
          paths:
            - node_modules

      - run: npx semantic-release



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - release